version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

